<?php
/*
 * Project-name: devqualimp
 * File-name: MouleModel.php
 * Author: WU
 * Start-Date: 2023/8/16 10:31
 */

namespace App\Models;

use CodeIgniter\Model;

class MouleModel extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->table = 'moule';
        $this->allowedFields = ['quali_code','cli_code','client','clientAdresse','reception_date','reception_path','dispatch_date','dispatch_path'];
    }

    public function insert($data = null, bool $returnID = true)
    {
        return parent::insert($data, $returnID); // TODO: Change the autogenerated stub
    }
}